package com.studyos.verify;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import org.junit.jupiter.api.Test;

class GroundingAuditTest {
    private static final String EVIDENCE = """
            [Source: lecture-03.pdf; pages 12-18]
            Section: 2 Cyclic codes > 2.1 Generator polynomials
            A cyclic code of length 15 over GF(2) is generated by a divisor of x^15 - 1. The minimum distance of
            the code in this example is 5, and the code corrects 2 errors.

            [Source: lecture-04.pdf; pages 3-4]
            Section: 3 Bounds
            The Hamming bound limits the number of codewords. For length 15 and distance 5 it gives at most 256
            codewords.
            """;

    private static List<String> claims(List<GroundingAudit.Finding> findings) {
        return findings.stream().map(GroundingAudit.Finding::claim).toList();
    }

    @Test void aFigureTheEvidenceStatesIsNotFlagged() {
        assertThat(GroundingAudit.findings("The minimum distance is 5 and the length is 15 [Source: lecture-03.pdf; pages 12-18].", EVIDENCE))
                .isEmpty();
    }

    @Test void aFigureTheEvidenceNeverStatesIsFlagged() {
        List<GroundingAudit.Finding> findings = GroundingAudit.findings(
                "The code corrects up to 37 errors [Source: lecture-03.pdf; pages 12-18].", EVIDENCE);
        assertThat(findings).hasSize(1);
        assertThat(findings.get(0).kind()).isEqualTo("figure not in the evidence");
        assertThat(findings.get(0).detail()).contains("\"37\"");
        assertThat(findings.get(0).reportable()).isTrue();
    }

    /** Only the learner-facing note is trimmed of signals; a figure finding is what the note is for. */
    @Test void theNoteNamesTheUnsupportedFigure() {
        String note = GroundingAudit.note(GroundingAudit.findings(
                "There are 512 codewords [Source: lecture-04.pdf; pages 3-4].", EVIDENCE));
        assertThat(note).contains("Grounding check").contains("512").contains("unverified");
    }

    /**
     * A sentence showing its arithmetic derived its numbers, and whether the derivation is right is the
     * computation audit's question. Checking it here would report every correct calculation as ungrounded.
     */
    @Test void aFigureTheSentenceDerivesIsLeftToTheComputationAudit() {
        assertThat(GroundingAudit.findings("Since d = 5, the code corrects (5 - 1) / 2 = 2 errors [Source: lecture-03.pdf; pages 12-18].", EVIDENCE))
                .isEmpty();
    }

    /** An uncited sentence has no source to be unfaithful to; that is the citation audit's recall question. */
    @Test void anUncitedSentenceIsNotChecked() {
        assertThat(GroundingAudit.findings("Some codes correct 37 errors.", EVIDENCE)).isEmpty();
    }

    @Test void aTurnWithNoEvidenceYieldsNothing() {
        assertThat(GroundingAudit.findings("There are 512 codewords [Source: ghost.pdf; pages 1-2].", "")).isEmpty();
        assertThat(GroundingAudit.findings("", EVIDENCE)).isEmpty();
    }

    /** A page number in the evidence header must not be able to attest a figure in an answer. */
    @Test void aPageNumberDoesNotAttestAFigure() {
        assertThat(claims(GroundingAudit.findings("The generator has degree 12 [Source: lecture-03.pdf; pages 12-18].", EVIDENCE)))
                .hasSize(1);
    }

    /** Decimal comma and decimal point are the same figure, so a localised answer is not flagged for its notation. */
    @Test void decimalNotationDoesNotMakeANewFigure() {
        String evidence = "[Source: stats.pdf; pages 1-2]\nThe rate is 0.75 of capacity.";
        assertThat(GroundingAudit.findings("The rate is 0,75 [Source: stats.pdf; pages 1-2].", evidence)).isEmpty();
    }

    /** Inflection is not a missing word: the evidence's "polynomials" supports a claim about a "polynomial". */
    @Test void inflectedWordingCountsAsPresent() {
        assertThat(GroundingAudit.findings("The generator polynomial divides the length-15 case [Source: lecture-03.pdf; pages 12-18].", EVIDENCE))
                .isEmpty();
    }

    /**
     * Wording is recorded, never shown. An answer is supposed to explain in its own words, so an unfamiliar term
     * is a measurement of this answer and telling a learner about it would be noise dressed as a warning.
     */
    @Test void unsupportedWordingIsRecordedButNotReported() {
        List<GroundingAudit.Finding> findings = GroundingAudit.findings(
                "Syndrome decoding exploits coset leaders through permutation equivalence [Source: lecture-03.pdf; pages 12-18].", EVIDENCE);
        assertThat(findings).isNotEmpty();
        assertThat(findings).allMatch(finding -> finding.kind().equals("wording not in the evidence"));
        assertThat(findings).noneMatch(GroundingAudit.Finding::reportable);
        assertThat(GroundingAudit.note(findings)).isEmpty();
    }

    /** One or two unfamiliar terms is a paraphrase, which is what an explanation in one's own words looks like. */
    @Test void aParaphraseIsNotUnsupportedWording() {
        assertThat(GroundingAudit.findings("The minimum distance of 5 is what limits correction here [Source: lecture-03.pdf; pages 12-18].", EVIDENCE))
                .isEmpty();
    }

    /** The citation carries a period and a semicolon of its own; neither may cut a claim from its reference. */
    @Test void aCitationsOwnPunctuationDoesNotSplitTheClaim() {
        assertThat(GroundingAudit.sentences("The code corrects 37 errors [Source: lecture-03.pdf; pages 12-18]. Next."))
                .containsExactly("The code corrects 37 errors [Source: lecture-03.pdf; pages 12-18].", " Next.");
    }

    /** The same wrong figure repeated is one defect, not one per repetition. */
    @Test void aRepeatedClaimIsReportedOnce() {
        String answer = "The code corrects 37 errors [Source: lecture-03.pdf; pages 12-18].\n"
                + "The code corrects 37 errors [Source: lecture-03.pdf; pages 12-18].";
        assertThat(GroundingAudit.findings(answer, EVIDENCE)).hasSize(1);
    }
}
