window.StudyOSApi = (() => {
  // The backend serves this page, so the API is whatever origin it came from. Never hardcode a port:
  // another app on this machine owns 8080, and a stale default would send StudyOS traffic to it.
  const base = localStorage.getItem('studyos-api-base') || (window.location.protocol.startsWith('http') ? window.location.origin : 'http://localhost:8081');
  async function request(path, options = {}) { const response = await fetch(`${base}${path}`, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) } }); if (!response.ok) { let detail = ''; try { const error = await response.json(); detail = error?.message || ''; } catch (_) {} const failure = new Error(`StudyOS API ${response.status}${detail ? `: ${detail}` : ''}`); failure.status = response.status; failure.detail = detail; throw failure; } return response.status === 204 ? null : response.json(); }
  return {
    base,
    health: () => request('/api/health'),
    listWorkspaces: () => request('/api/workspaces'),
    createWorkspace: (workspace) => request('/api/workspaces', { method: 'POST', body: JSON.stringify(workspace) }),
    getWorkspace: (workspaceId) => request(`/api/workspaces/${workspaceId}`),
    updateWorkspace: (workspaceId, workspace) => request(`/api/workspaces/${workspaceId}`, { method: 'PATCH', body: JSON.stringify(workspace) }),
    deleteWorkspace: (workspaceId) => request(`/api/workspaces/${workspaceId}`, { method: 'DELETE' }),
    listCourses: () => request('/api/courses'),
    createCourse: (course) => request('/api/courses', { method: 'POST', body: JSON.stringify(course) }),
    createChat: (workspaceId, title, purpose = null) => request(`/api/workspaces/${workspaceId}/chats`, { method: 'POST', body: JSON.stringify({ title, purpose }) }),
    listChats: (workspaceId) => request(`/api/workspaces/${workspaceId}/chats`),
    listChatPurposes: (workspaceId) => request(`/api/workspaces/${workspaceId}/chats/purposes`),
    listMessages: (workspaceId, chatId) => request(`/api/workspaces/${workspaceId}/chats/${chatId}/messages`),
    sendMessage: (workspaceId, chatId, content) => request(`/api/workspaces/${workspaceId}/chats/${chatId}/messages`, { method: 'POST', body: JSON.stringify({ content }) }),
    listSources: (workspaceId) => request(`/api/workspaces/${workspaceId}/sources`),
    deleteSource: (workspaceId, documentId) => request(`/api/workspaces/${workspaceId}/sources/${documentId}`, { method: 'DELETE' }),
    uploadSource: (workspaceId, file, type = 'OTHER') => { const form = new FormData(); form.append('file', file); return request(`/api/workspaces/${workspaceId}/sources?type=${type}`, { method: 'POST', body: form }); },
    pasteSource: (workspaceId, source) => request(`/api/workspaces/${workspaceId}/sources/text`, { method: 'POST', body: JSON.stringify(source) }),
    listTopics: (workspaceId) => request(`/api/workspaces/${workspaceId}/topics`),
    listTopicCapsules: (workspaceId) => request(`/api/workspaces/${workspaceId}/topic-capsules`),
    getTopicCapsule: (workspaceId, topicId) => request(`/api/workspaces/${workspaceId}/topic-capsules/${topicId}`),
    benchmarkRetrieval: (workspaceId, cases) => request(`/api/workspaces/${workspaceId}/retrieval/benchmark`, { method: 'POST', body: JSON.stringify({ cases }) }),
    rebuildTopics: (workspaceId) => request(`/api/workspaces/${workspaceId}/topics/rebuild`, { method: 'POST' }),
    topicRebuildStatus: (workspaceId) => request(`/api/workspaces/${workspaceId}/topics/rebuild/status`),
    reconcileTopics: (workspaceId) => request(`/api/workspaces/${workspaceId}/topics/reconcile`, { method: 'POST' }),
    listTopicObjectives: (workspaceId, topicId) => request(`/api/workspaces/${workspaceId}/topics/${topicId}/objectives`),
    listTopicRelations: (workspaceId) => request(`/api/workspaces/${workspaceId}/topics/relations`),
    listSummaries: (workspaceId) => request(`/api/workspaces/${workspaceId}/summaries`),
    rebuildSummaries: (workspaceId) => request(`/api/workspaces/${workspaceId}/summaries/rebuild`, { method: 'POST' }),
    listLearningEvents: (workspaceId) => request(`/api/workspaces/${workspaceId}/learning-evidence`),
    getPredictions: (workspaceId) => request(`/api/workspaces/${workspaceId}/predictions`),
    getLearnerState: (workspaceId) => request(`/api/workspaces/${workspaceId}/learner-state`),
    setLearningPreference: (workspaceId, key, value) => request(`/api/workspaces/${workspaceId}/learner-state/preferences/${encodeURIComponent(key)}`, { method: 'PUT', body: JSON.stringify({ value }) }),
    resolveMisconception: (workspaceId, misconceptionId) => request(`/api/workspaces/${workspaceId}/learner-state/misconceptions/${misconceptionId}/resolve`, { method: 'POST' }),
    getExamAnalysis: (workspaceId) => request(`/api/workspaces/${workspaceId}/exam-analysis`),
    rebuildExamAnalysis: (workspaceId) => request(`/api/workspaces/${workspaceId}/exam-analysis/rebuild`, { method: 'POST' }),
    getExamPredictions: (workspaceId) => request(`/api/workspaces/${workspaceId}/exam-predictions`),
    getExamBacktest: (workspaceId) => request(`/api/workspaces/${workspaceId}/exam-predictions/backtest`),
    createMockExam: (workspaceId, payload = {}) => request(`/api/workspaces/${workspaceId}/mock-exams`, { method: 'POST', body: JSON.stringify(payload) }),
    startMockExam: (workspaceId, examId) => request(`/api/workspaces/${workspaceId}/mock-exams/${examId}/start`, { method: 'POST' }),
    completeMockExam: (workspaceId, examId) => request(`/api/workspaces/${workspaceId}/mock-exams/${examId}/complete`, { method: 'POST' }),
    listAssessments: (workspaceId, sourceType = '') => request(`/api/workspaces/${workspaceId}/assessments${sourceType ? `?sourceType=${encodeURIComponent(sourceType)}` : ''}`),
    listMisconceptions: (workspaceId) => request(`/api/workspaces/${workspaceId}/misconceptions`),
    getOverview: (workspaceId) => request(`/api/workspaces/${workspaceId}/overview`),
    getStudyPlan: (workspaceId, date = new Date().toISOString().slice(0, 10)) => request(`/api/workspaces/${workspaceId}/study-plan?date=${encodeURIComponent(date)}`),
    generateStudyPlan: (workspaceId, availableMinutes = 120, date = new Date().toISOString().slice(0, 10)) => request(`/api/workspaces/${workspaceId}/study-plans/generate`, { method: 'POST', body: JSON.stringify({ date, availableMinutes }) }),
    getStudyTask: (workspaceId, taskId) => request(`/api/workspaces/${workspaceId}/study-tasks/${taskId}`),
    startStudySession: (workspaceId, payload = {}) => request(`/api/workspaces/${workspaceId}/sessions`, { method: 'POST', body: JSON.stringify(payload) }),
    completeStudySession: (workspaceId, sessionId, payload = {}) => request(`/api/workspaces/${workspaceId}/sessions/${sessionId}/complete`, { method: 'POST', body: JSON.stringify(payload) }),
    generateQuiz: (workspaceId, payload) => request(`/api/workspaces/${workspaceId}/quiz`, { method: 'POST', body: JSON.stringify(payload) }),
    submitAnswer: (workspaceId, itemId, answer) => request(`/api/workspaces/${workspaceId}/quiz/${itemId}/attempts`, { method: 'POST', body: JSON.stringify({ answer }) }),
    getExerciseSupport: (workspaceId, itemId, level = 1) => request(`/api/workspaces/${workspaceId}/quiz/${itemId}/support?level=${encodeURIComponent(level)}`),
    getCurriculum: (workspaceId) => request(`/api/workspaces/${workspaceId}/curriculum`),
    generateCurriculum: (workspaceId, goal = null) => request(`/api/workspaces/${workspaceId}/curriculum`, { method: 'POST', body: JSON.stringify({ goal }) }),
    getCurriculumFrontier: (workspaceId) => request(`/api/workspaces/${workspaceId}/curriculum/frontier`),
    getPacing: (workspaceId, minutesPerDay = null, daysPerWeek = null) => request(`/api/workspaces/${workspaceId}/curriculum/pacing${minutesPerDay ? `?minutesPerDay=${encodeURIComponent(minutesPerDay)}${daysPerWeek ? `&daysPerWeek=${encodeURIComponent(daysPerWeek)}` : ''}` : ''}`),
    getIntegrity: (workspaceId) => request(`/api/workspaces/${workspaceId}/curriculum/integrity`),
    repairIntegrity: (workspaceId) => request(`/api/workspaces/${workspaceId}/curriculum/integrity/repair`, { method: 'POST' }),
    getReplanSuggestions: (workspaceId) => request(`/api/workspaces/${workspaceId}/curriculum/replan/suggestions`),
    replanCurriculum: (workspaceId, reason = null) => request(`/api/workspaces/${workspaceId}/curriculum/replan`, { method: 'POST', body: JSON.stringify({ reason }) }),
    getLessonBrief: (workspaceId, lessonId) => request(`/api/workspaces/${workspaceId}/curriculum/lessons/${lessonId}/brief`),
    rewriteLessonBrief: (workspaceId, lessonId) => request(`/api/workspaces/${workspaceId}/curriculum/lessons/${lessonId}/brief`, { method: 'POST' }),
    getSyllabus: (workspaceId) => request(`/api/workspaces/${workspaceId}/syllabus`),
    getLadderLevels: (workspaceId) => request(`/api/workspaces/${workspaceId}/ladder/levels`),
    listLadder: (workspaceId) => request(`/api/workspaces/${workspaceId}/ladder`),
    getTopicLadder: (workspaceId, topicId) => request(`/api/workspaces/${workspaceId}/ladder/topics/${topicId}`),
    getTodaySession: (workspaceId, minutes = null) => request(`/api/workspaces/${workspaceId}/tutor/today${minutes ? `?minutes=${encodeURIComponent(minutes)}` : ''}`),
    startTutorSession: (workspaceId, minutes = null) => request(`/api/workspaces/${workspaceId}/tutor/sessions`, { method: 'POST', body: JSON.stringify({ minutes }) }),
    listTutorSessions: (workspaceId) => request(`/api/workspaces/${workspaceId}/tutor/sessions`),
    getTutorSession: (workspaceId, sessionId) => request(`/api/workspaces/${workspaceId}/tutor/sessions/${sessionId}`),
    advanceTutorStep: (workspaceId, sessionId, ordinal, outcome = {}) => request(`/api/workspaces/${workspaceId}/tutor/sessions/${sessionId}/steps/${ordinal}/advance`, { method: 'POST', body: JSON.stringify(outcome) }),
    completeTutorSession: (workspaceId, sessionId) => request(`/api/workspaces/${workspaceId}/tutor/sessions/${sessionId}/complete`, { method: 'POST' }),
    getExamMode: (workspaceId, minutes = null) => request(`/api/workspaces/${workspaceId}/tutor/exam-mode${minutes ? `?minutes=${encodeURIComponent(minutes)}` : ''}`),
    getLearnerProfile: (workspaceId) => request(`/api/workspaces/${workspaceId}/learner-state/profile`),
    refreshLearnerProfile: (workspaceId) => request(`/api/workspaces/${workspaceId}/learner-state/profile/refresh`, { method: 'POST' }),
    completeStudyTask: (taskId, payload = {}) => request(`/api/study-tasks/${taskId}/complete`, { method: 'POST', body: JSON.stringify(payload) }),
    startResearch: (workspaceId, payload) => request(`/api/workspaces/${workspaceId}/research`, { method: 'POST', body: JSON.stringify(payload) }),
    getResearchStatus: (workspaceId) => request(`/api/workspaces/${workspaceId}/research`),
    getResearchCoverage: (workspaceId) => request(`/api/workspaces/${workspaceId}/research/coverage`),
    getDiagnostics: (workspaceId, kind = 'learning') => request(`/api/workspaces/${workspaceId}/diagnostics/${encodeURIComponent(kind)}`)
  };
})();
