package com.studyos.chat;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

/** Structured result from the strict batch verifier. */
public record PredictionVerificationBatch(@JsonAlias({"verifications","results","items"}) List<Verification> candidates) {
    public PredictionVerificationBatch { candidates=candidates==null?List.of():List.copyOf(candidates); }
    public static String contract() { return "Return JSON {candidates:[{candidateId,requiredConcepts,supportedConcepts,unsupportedConcepts,unsupportedModelChanges,scopeViolation,groundingOk,wellDefined,mathematicalConsistency,missingSpecification,validationIssues,noveltyType,reasoningNovelty,nearCopy,plausibilityReasoning,confidence,candidateSemantics:"+AcademicSemanticProfile.contract()+",unsupportedAssumptions,unsupportedDomains,unsupportedOperations,solutionStrategySimilarity,reasoningDifficulty,difficultyReason,conceptEvidence:{\"material candidate assumption\":\"short exact quote copied from supplied source evidence\"}}]}. Use at most 4 concise phrases in each semantic array and at most 6 in diagnostic arrays. Extract candidateSemantics from the candidate. candidateSemantics.taskTypes and expectedReasoningSteps must contain only work explicitly requested by the candidate, never tasks copied from source/reference context. In candidateSemantics.operations include only operations/rules of the academic model or scenario; put task verbs such as prove, analyze, derive, compare, or critique in taskTypes instead. groundingOk is true only if every materially required academic concept, model assumption, domain/type, operation/rule, and knowledge item is supported by supplied scope evidence. Generic reasoning forms explicitly authorized by the system policy—such as characterize, prove both directions, find a counterexample, analyze uniqueness, or audit and repair a proof—belong in taskTypes and are not unsupported academic concepts merely because the source did not ask that task before. conceptEvidence must contain a short exact source quote for every academic/model item in candidateSemantics.assumptions; never use candidate text or prior generated text as evidence. noveltyType is EXACT_COPY, NEAR_COPY, PARAMETER_ONLY_VARIANT, SHALLOW_TRANSFORMATION, MEANINGFUL_TRANSFORMATION, or NEW_REASONING. solutionStrategySimilarity, reasoningDifficulty, reasoningNovelty, and confidence are numbers from 0 to 1."; }
    public record Verification(String candidateId,@JsonDeserialize(using=StringListDeserializer.class) List<String> requiredConcepts,@JsonDeserialize(using=StringListDeserializer.class) List<String> supportedConcepts,@JsonDeserialize(using=StringListDeserializer.class) List<String> unsupportedConcepts,@JsonDeserialize(using=StringListDeserializer.class) List<String> unsupportedModelChanges,@JsonDeserialize(using=FlexibleBooleanDeserializer.class) boolean scopeViolation,@JsonDeserialize(using=FlexibleBooleanDeserializer.class) boolean groundingOk,@JsonDeserialize(using=FlexibleBooleanDeserializer.class) boolean wellDefined,@JsonDeserialize(using=FlexibleBooleanDeserializer.class) Boolean mathematicalConsistency,@JsonDeserialize(using=StringListDeserializer.class) List<String> missingSpecification,@JsonDeserialize(using=StringListDeserializer.class) List<String> validationIssues,String noveltyType,Double reasoningNovelty,@JsonDeserialize(using=FlexibleBooleanDeserializer.class) boolean nearCopy,String plausibilityReasoning,Double confidence,AcademicSemanticProfile candidateSemantics,@JsonDeserialize(using=StringListDeserializer.class) List<String> unsupportedAssumptions,@JsonDeserialize(using=StringListDeserializer.class) List<String> unsupportedDomains,@JsonDeserialize(using=StringListDeserializer.class) List<String> unsupportedOperations,Double solutionStrategySimilarity,Double reasoningDifficulty,String difficultyReason,Map<String,String> conceptEvidence) {
        public Verification { candidateId=candidateId==null?"":candidateId.trim(); requiredConcepts=copy(requiredConcepts); supportedConcepts=copy(supportedConcepts); unsupportedConcepts=copy(unsupportedConcepts); unsupportedModelChanges=copy(unsupportedModelChanges); mathematicalConsistency=Boolean.TRUE.equals(mathematicalConsistency); missingSpecification=copy(missingSpecification); validationIssues=copy(validationIssues); noveltyType=noveltyType==null?"NEAR_COPY":noveltyType.trim(); plausibilityReasoning=plausibilityReasoning==null?"":plausibilityReasoning.trim(); reasoningNovelty=clamp(reasoningNovelty); confidence=clamp(confidence);candidateSemantics=candidateSemantics==null?AcademicSemanticProfile.empty():candidateSemantics;unsupportedAssumptions=copy(unsupportedAssumptions);unsupportedDomains=copy(unsupportedDomains);unsupportedOperations=copy(unsupportedOperations);solutionStrategySimilarity=clamp(solutionStrategySimilarity);reasoningDifficulty=reasoningDifficulty==null?reasoningNovelty:clamp(reasoningDifficulty);difficultyReason=difficultyReason==null?"":difficultyReason.trim();conceptEvidence=copyMap(conceptEvidence); }
        public Verification(String candidateId,List<String> requiredConcepts,List<String> supportedConcepts,List<String> unsupportedConcepts,List<String> unsupportedModelChanges,boolean scopeViolation,boolean groundingOk,boolean wellDefined,Boolean mathematicalConsistency,List<String> missingSpecification,List<String> validationIssues,String noveltyType,Double reasoningNovelty,boolean nearCopy,String plausibilityReasoning,Double confidence,AcademicSemanticProfile candidateSemantics,List<String> unsupportedAssumptions,List<String> unsupportedDomains,List<String> unsupportedOperations,Double solutionStrategySimilarity,Double reasoningDifficulty,String difficultyReason){this(candidateId,requiredConcepts,supportedConcepts,unsupportedConcepts,unsupportedModelChanges,scopeViolation,groundingOk,wellDefined,mathematicalConsistency,missingSpecification,validationIssues,noveltyType,reasoningNovelty,nearCopy,plausibilityReasoning,confidence,candidateSemantics,unsupportedAssumptions,unsupportedDomains,unsupportedOperations,solutionStrategySimilarity,reasoningDifficulty,difficultyReason,Map.of());}
        public Verification(String candidateId,List<String> requiredConcepts,List<String> supportedConcepts,List<String> unsupportedConcepts,List<String> unsupportedModelChanges,boolean scopeViolation,boolean groundingOk,boolean wellDefined,Boolean mathematicalConsistency,List<String> missingSpecification,List<String> validationIssues,String noveltyType,Double reasoningNovelty,boolean nearCopy,String plausibilityReasoning,Double confidence){this(candidateId,requiredConcepts,supportedConcepts,unsupportedConcepts,unsupportedModelChanges,scopeViolation,groundingOk,wellDefined,mathematicalConsistency,missingSpecification,validationIssues,noveltyType,reasoningNovelty,nearCopy,plausibilityReasoning,confidence,AcademicSemanticProfile.empty(),List.of(),List.of(),List.of(),nearCopy?1d:.5d,reasoningNovelty,"",Map.of());}
        public Verification(String candidateId,boolean groundingOk,List<String> unsupportedConcepts,boolean wellDefined,List<String> missingSpecification,List<String> validationIssues,String noveltyType,Double reasoningNovelty,boolean nearCopy,String plausibilityReasoning,Double confidence){this(candidateId,List.of(),List.of(),unsupportedConcepts,List.of(),false,groundingOk,wellDefined,true,missingSpecification,validationIssues,noveltyType,reasoningNovelty,nearCopy,plausibilityReasoning,confidence);}
        private static Double clamp(Double value) { return value==null?0d:Math.max(0,Math.min(1,value)); }
        private static List<String> copy(List<String> values){return values==null?List.of():List.copyOf(values);}
        private static Map<String,String> copyMap(Map<String,String> values){if(values==null||values.isEmpty())return Map.of();Map<String,String> result=new LinkedHashMap<>();values.forEach((key,value)->{if(key!=null&&!key.isBlank()&&value!=null&&!value.isBlank())result.put(key.trim(),value.trim());});return Map.copyOf(result);}
    }
    /** NVIDIA occasionally returns false for an empty issue list; preserve strict semantics without failing the whole batch. */
    public static final class StringListDeserializer extends JsonDeserializer<List<String>> {
        @Override public List<String> deserialize(JsonParser parser,DeserializationContext context) throws IOException { JsonNode node=parser.getCodec().readTree(parser); if(node.isNull()||node.isBoolean()&&!node.asBoolean())return List.of(); List<String> values=new ArrayList<>();if(node.isArray())node.forEach(value->{if(!value.isNull())values.add(value.asText());});else if(node.isTextual()&&!node.asText().isBlank())values.add(node.asText());return List.copyOf(values); }
    }
    /** Accepts provider variants such as a textual scope-violation reason as a truthy value. */
    public static final class FlexibleBooleanDeserializer extends JsonDeserializer<Boolean> {
        @Override public Boolean deserialize(JsonParser parser,DeserializationContext context) throws IOException { JsonNode node=parser.getCodec().readTree(parser);if(node.isBoolean())return node.asBoolean();if(node.isNumber())return node.asInt()!=0;if(node.isNull())return false;String value=node.asText("").trim();return !(value.isEmpty()||value.equalsIgnoreCase("false")||value.equals("0")||value.equalsIgnoreCase("no")||value.equalsIgnoreCase("none")); }
    }
}
