CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE courses (id UUID PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, exam_date DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE documents (id UUID PRIMARY KEY, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, name VARCHAR(500) NOT NULL, document_type VARCHAR(50) NOT NULL, storage_path TEXT NOT NULL, status VARCHAR(50) NOT NULL, language VARCHAR(20), page_count INTEGER, content_hash VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), processed_at TIMESTAMPTZ);
CREATE INDEX idx_documents_course ON documents(course_id);
CREATE TABLE document_sections (id UUID PRIMARY KEY, document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE, parent_section_id UUID REFERENCES document_sections(id) ON DELETE CASCADE, title TEXT, level INTEGER NOT NULL, ordinal INTEGER NOT NULL, page_start INTEGER, page_end INTEGER, raw_text TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE chunks (id UUID PRIMARY KEY, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE, section_id UUID REFERENCES document_sections(id) ON DELETE SET NULL, ordinal INTEGER NOT NULL, page_start INTEGER, page_end INTEGER, content TEXT NOT NULL, token_count INTEGER, content_hash VARCHAR(64), embedding vector(1536), metadata JSONB NOT NULL DEFAULT '{}'::jsonb, search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_chunks_course ON chunks(course_id);
CREATE INDEX idx_chunks_search ON chunks USING GIN(search_vector);
CREATE INDEX idx_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops);
CREATE TABLE topics (id UUID PRIMARY KEY, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, canonical_name VARCHAR(500) NOT NULL, normalized_name VARCHAR(500) NOT NULL, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(course_id, normalized_name));
CREATE TABLE topic_edges (id UUID PRIMARY KEY, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, source_topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE, target_topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE, relation_type VARCHAR(50) NOT NULL, confidence DOUBLE PRECISION, source_chunk_id UUID REFERENCES chunks(id) ON DELETE SET NULL);
CREATE TABLE chunk_topics (chunk_id UUID NOT NULL REFERENCES chunks(id) ON DELETE CASCADE, topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE, relevance DOUBLE PRECISION NOT NULL, PRIMARY KEY(chunk_id, topic_id));
CREATE TABLE student_topic_state (course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE, mastery DOUBLE PRECISION NOT NULL DEFAULT 0, confidence DOUBLE PRECISION NOT NULL DEFAULT 0, review_due_at TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(course_id, topic_id));
CREATE TABLE learning_events (id UUID PRIMARY KEY, course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, topic_id UUID REFERENCES topics(id) ON DELETE SET NULL, event_type VARCHAR(50) NOT NULL, payload JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE ingestion_jobs (id UUID PRIMARY KEY, document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE, status VARCHAR(50) NOT NULL, current_stage VARCHAR(100), progress INTEGER NOT NULL DEFAULT 0, error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ);
