ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS course_id UUID REFERENCES courses(id) ON DELETE SET NULL;
ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS chat_id UUID REFERENCES chats(id) ON DELETE SET NULL;
ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS provider VARCHAR(50);
ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS success BOOLEAN NOT NULL DEFAULT TRUE;
CREATE INDEX IF NOT EXISTS idx_ai_usage_course ON ai_usage(course_id, created_at DESC);
