import type { RuntimeContentPack } from '../ai/runtime-knowledge.js';

/**
 * Goal-category keyword lexicon — the exact content of the legacy inline
 * `KEYWORDS` table (category.ts), unchanged. Roles are GOAL_CATEGORY values;
 * the consumer maps them through the generic persisted-category filter.
 * Matching semantics live with the consumer: this family is scored by literal
 * substring inclusion, exactly as before.
 */
export const goalCategoryPack: RuntimeContentPack = {
  kind: 'lexicon',
  pack: {
    key: 'goal-category',
    entries: [
      // FITNESS
      { phrase: 'fitness', role: 'FITNESS' },
      { phrase: 'fitter', role: 'FITNESS' },
      { phrase: 'get fit', role: 'FITNESS' },
      { phrase: 'gym', role: 'FITNESS' },
      { phrase: 'workout', role: 'FITNESS' },
      { phrase: 'exercise', role: 'FITNESS' },
      { phrase: 'run', role: 'FITNESS' },
      { phrase: 'jog', role: 'FITNESS' },
      { phrase: 'walk', role: 'FITNESS' },
      { phrase: 'swim', role: 'FITNESS' },
      { phrase: 'cycle', role: 'FITNESS' },
      { phrase: 'cycling', role: 'FITNESS' },
      { phrase: 'weight', role: 'FITNESS' },
      { phrase: 'muscle', role: 'FITNESS' },
      { phrase: 'strength', role: 'FITNESS' },
      { phrase: 'cardio', role: 'FITNESS' },
      { phrase: 'yoga', role: 'FITNESS' },
      { phrase: 'pilates', role: 'FITNESS' },
      { phrase: 'steps', role: 'FITNESS' },
      { phrase: 'marathon', role: 'FITNESS' },
      { phrase: '5k', role: 'FITNESS' },
      { phrase: '10k', role: 'FITNESS' },
      { phrase: 'training', role: 'FITNESS' },
      { phrase: 'lose weight', role: 'FITNESS' },
      { phrase: 'get in shape', role: 'FITNESS' },
      // HEALTH
      { phrase: 'health', role: 'HEALTH' },
      { phrase: 'sleep', role: 'HEALTH' },
      { phrase: 'water', role: 'HEALTH' },
      { phrase: 'hydrat', role: 'HEALTH' },
      { phrase: 'meditat', role: 'HEALTH' },
      { phrase: 'stress', role: 'HEALTH' },
      { phrase: 'anxiety', role: 'HEALTH' },
      { phrase: 'diet', role: 'HEALTH' },
      { phrase: 'nutrition', role: 'HEALTH' },
      { phrase: 'eat', role: 'HEALTH' },
      { phrase: 'smoking', role: 'HEALTH' },
      { phrase: 'quit smoking', role: 'HEALTH' },
      { phrase: 'alcohol', role: 'HEALTH' },
      { phrase: 'mindful', role: 'HEALTH' },
      { phrase: 'therapy', role: 'HEALTH' },
      { phrase: 'doctor', role: 'HEALTH' },
      { phrase: 'wellbeing', role: 'HEALTH' },
      { phrase: 'wellness', role: 'HEALTH' },
      // STUDY
      { phrase: 'study', role: 'STUDY' },
      { phrase: 'exam', role: 'STUDY' },
      { phrase: 'revise', role: 'STUDY' },
      { phrase: 'revision', role: 'STUDY' },
      { phrase: 'course', role: 'STUDY' },
      { phrase: 'university', role: 'STUDY' },
      { phrase: 'college', role: 'STUDY' },
      { phrase: 'school', role: 'STUDY' },
      { phrase: 'degree', role: 'STUDY' },
      { phrase: 'homework', role: 'STUDY' },
      { phrase: 'lecture', role: 'STUDY' },
      { phrase: 'semester', role: 'STUDY' },
      { phrase: 'test', role: 'STUDY' },
      { phrase: 'certification', role: 'STUDY' },
      // READING
      { phrase: 'read', role: 'READING' },
      { phrase: 'book', role: 'READING' },
      { phrase: 'novel', role: 'READING' },
      { phrase: 'literature', role: 'READING' },
      { phrase: 'pages', role: 'READING' },
      { phrase: 'kindle', role: 'READING' },
      { phrase: 'audiobook', role: 'READING' },
      // CAREER
      { phrase: 'career', role: 'CAREER' },
      { phrase: 'job', role: 'CAREER' },
      { phrase: 'work', role: 'CAREER' },
      { phrase: 'promotion', role: 'CAREER' },
      { phrase: 'interview', role: 'CAREER' },
      { phrase: 'resume', role: 'CAREER' },
      { phrase: 'cv', role: 'CAREER' },
      { phrase: 'portfolio', role: 'CAREER' },
      { phrase: 'network', role: 'CAREER' },
      { phrase: 'freelance', role: 'CAREER' },
      { phrase: 'business', role: 'CAREER' },
      { phrase: 'startup', role: 'CAREER' },
      { phrase: 'client', role: 'CAREER' },
      { phrase: 'linkedin', role: 'CAREER' },
      // FINANCE
      { phrase: 'save', role: 'FINANCE' },
      { phrase: 'saving', role: 'FINANCE' },
      { phrase: 'money', role: 'FINANCE' },
      { phrase: 'budget', role: 'FINANCE' },
      { phrase: 'debt', role: 'FINANCE' },
      { phrase: 'spend', role: 'FINANCE' },
      { phrase: 'spending', role: 'FINANCE' },
      { phrase: 'expense', role: 'FINANCE' },
      { phrase: 'salary', role: 'FINANCE' },
      { phrase: 'cash', role: 'FINANCE' },
      { phrase: 'afford', role: 'FINANCE' },
      { phrase: 'financ', role: 'FINANCE' },
      { phrase: 'bill', role: 'FINANCE' },
      { phrase: 'subscription', role: 'FINANCE' },
      { phrase: 'cost', role: 'FINANCE' },
      { phrase: '$', role: 'FINANCE' },
      { phrase: '€', role: 'FINANCE' },
      { phrase: '£', role: 'FINANCE' },
      // PRODUCTIVITY
      { phrase: 'productiv', role: 'PRODUCTIVITY' },
      { phrase: 'focus', role: 'PRODUCTIVITY' },
      { phrase: 'procrastinat', role: 'PRODUCTIVITY' },
      { phrase: 'organis', role: 'PRODUCTIVITY' },
      { phrase: 'organiz', role: 'PRODUCTIVITY' },
      { phrase: 'routine', role: 'PRODUCTIVITY' },
      { phrase: 'habit', role: 'PRODUCTIVITY' },
      { phrase: 'time management', role: 'PRODUCTIVITY' },
      { phrase: 'planning', role: 'PRODUCTIVITY' },
      { phrase: 'inbox', role: 'PRODUCTIVITY' },
      { phrase: 'declutter', role: 'PRODUCTIVITY' },
      { phrase: 'tidy', role: 'PRODUCTIVITY' },
      { phrase: 'morning routine', role: 'PRODUCTIVITY' },
      // PERSONAL
      { phrase: 'learn', role: 'PERSONAL' },
      { phrase: 'language', role: 'PERSONAL' },
      { phrase: 'spanish', role: 'PERSONAL' },
      { phrase: 'french', role: 'PERSONAL' },
      { phrase: 'german', role: 'PERSONAL' },
      { phrase: 'guitar', role: 'PERSONAL' },
      { phrase: 'piano', role: 'PERSONAL' },
      { phrase: 'paint', role: 'PERSONAL' },
      { phrase: 'draw', role: 'PERSONAL' },
      { phrase: 'write', role: 'PERSONAL' },
      { phrase: 'writing', role: 'PERSONAL' },
      { phrase: 'hobby', role: 'PERSONAL' },
      { phrase: 'skill', role: 'PERSONAL' },
      { phrase: 'instrument', role: 'PERSONAL' },
      { phrase: 'cook', role: 'PERSONAL' },
      { phrase: 'garden', role: 'PERSONAL' },
      { phrase: 'photography', role: 'PERSONAL' },
      { phrase: 'dance', role: 'PERSONAL' },
      { phrase: 'dancing', role: 'PERSONAL' },
      { phrase: 'chess', role: 'PERSONAL' },
      { phrase: 'code', role: 'PERSONAL' },
      { phrase: 'programming', role: 'PERSONAL' },
      // OTHER: no keywords — the legacy table's empty entry
    ],
  },
};
