package com.studyos.knowledge;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/** Persists source-derived capsule content; live learner state is merged at read time. */
@Service
public class TopicCapsuleService {
    private final JdbcTemplate jdbc; private final ObjectMapper mapper;
    public TopicCapsuleService(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    public List<Capsule> list(UUID courseId){return jdbc.query("SELECT id FROM topics WHERE course_id=? ORDER BY canonical_name",(rs,row)->capsule(courseId,rs.getObject(1,UUID.class)),courseId);}
    public Capsule get(UUID courseId,UUID topicId){Capsule result=capsule(courseId,topicId);if(result==null)throw new IllegalArgumentException("Topic was not found");return result;}
    public int rebuild(UUID courseId){String version=sourceVersion(courseId);List<UUID> topics=jdbc.query("SELECT id FROM topics WHERE course_id=?",(rs,row)->rs.getObject(1,UUID.class),courseId);for(UUID topic:topics)persist(courseId,topic,version,buildStatic(courseId,topic));return topics.size();}
    private Capsule capsule(UUID courseId,UUID topicId){Topic topic=jdbc.query("SELECT id,canonical_name,description FROM topics WHERE id=? AND course_id=?",rs->rs.next()?new Topic(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3)):null,topicId,courseId);if(topic==null)return null;StaticCapsule statics=cached(courseId,topicId);List<Misconception> misconceptions=jdbc.query("SELECT label,status,occurrences,severity FROM misconceptions WHERE course_id=? AND topic_id=? AND status<>'RESOLVED' ORDER BY severity DESC",(rs,row)->new Misconception(rs.getString(1),rs.getString(2),rs.getInt(3),rs.getDouble(4)),courseId,topicId);State state=jdbc.query("SELECT COALESCE(measured_mastery,mastery,0),COALESCE(retention_estimate,1) FROM student_topic_state WHERE course_id=? AND topic_id=?",rs->rs.next()?new State(rs.getDouble(1),rs.getDouble(2)):new State(0,1),courseId,topicId);return new Capsule(topic.id(),topic.name(),statics.summary(),statics.prerequisites(),statics.sources(),statics.assessmentPatterns(),state.measured(),state.retention(),state.measured()*state.retention(),misconceptions);}
    private StaticCapsule cached(UUID courseId,UUID topicId){String version=sourceVersion(courseId);String payload=jdbc.query("SELECT static_payload::text FROM topic_capsule_cache WHERE course_id=? AND topic_id=? AND source_version=?",rs->rs.next()?rs.getString(1):null,courseId,topicId,version);if(payload!=null)try{return mapper.readValue(payload,StaticCapsule.class);}catch(Exception ignored){} StaticCapsule created=buildStatic(courseId,topicId);persist(courseId,topicId,version,created);return created;}
    private StaticCapsule buildStatic(UUID courseId,UUID topicId){String fallback=jdbc.query("SELECT description FROM topics WHERE id=?",rs->rs.next()?rs.getString(1):null,topicId);List<SourceStat> sources=jdbc.query("SELECT d.document_type,COUNT(DISTINCT d.id) FROM chunk_topics ct JOIN chunks c ON c.id=ct.chunk_id JOIN documents d ON d.id=c.document_id WHERE ct.topic_id=? GROUP BY d.document_type ORDER BY d.document_type",(rs,row)->new SourceStat(rs.getString(1),rs.getLong(2)),topicId);List<QuestionPattern> patterns=jdbc.query("SELECT ai.type,COUNT(*) FROM assessment_item_topics ait JOIN assessment_items ai ON ai.id=ait.item_id WHERE ait.topic_id=? GROUP BY ai.type ORDER BY COUNT(*) DESC",(rs,row)->new QuestionPattern(rs.getString(1),rs.getLong(2)),topicId);List<String> prerequisites=jdbc.query("SELECT DISTINCT t.canonical_name FROM topic_prerequisites e JOIN topics t ON t.id=e.prerequisite_topic_id WHERE e.course_id=? AND e.dependent_topic_id=? ORDER BY t.canonical_name",(rs,row)->rs.getString(1),courseId,topicId);return new StaticCapsule(summary(topicId,fallback),prerequisites,sources,patterns);}
    private void persist(UUID courseId,UUID topicId,String version,StaticCapsule value){try{jdbc.update("INSERT INTO topic_capsule_cache(course_id,topic_id,source_version,static_payload,updated_at) VALUES(?,?,?,?::jsonb,NOW()) ON CONFLICT(course_id,topic_id) DO UPDATE SET source_version=EXCLUDED.source_version,static_payload=EXCLUDED.static_payload,updated_at=NOW()",courseId,topicId,version,mapper.writeValueAsString(value));}catch(Exception error){throw new IllegalStateException("Cannot persist topic capsule",error);}}
    private String summary(UUID topicId,String fallback){List<String> chunks=jdbc.query("SELECT c.content FROM chunk_topics ct JOIN chunks c ON c.id=ct.chunk_id WHERE ct.topic_id=? ORDER BY ct.relevance DESC LIMIT 3",(rs,row)->rs.getString(1),topicId);String text=chunks.stream().map(value->value.replaceAll("\\s+"," ").trim()).filter(value->!value.isBlank()).reduce("",(a,b)->a.isBlank()?b:a+" "+b);if(text.isBlank())text=fallback==null?"No source summary available yet.":fallback;return String.join(" ",Arrays.stream(text.split("(?<=[.!?])\\s+")).limit(3).map(sentence->sentence.length()>300?sentence.substring(0,300)+"...":sentence).toList());}
    private String sourceVersion(UUID courseId){List<String> values=new ArrayList<>(jdbc.query("SELECT COALESCE(content_hash,'') FROM documents WHERE course_id=? AND status='COMPLETED' ORDER BY id",(rs,row)->rs.getString(1),courseId));values.addAll(jdbc.query("SELECT source_topic_id::text||':'||target_topic_id::text||':'||relation_type FROM topic_edges WHERE course_id=? ORDER BY source_topic_id,target_topic_id,relation_type",(rs,row)->rs.getString(1),courseId));try{byte[] digest=MessageDigest.getInstance("SHA-256").digest(String.join("|",values).getBytes(StandardCharsets.UTF_8));StringBuilder result=new StringBuilder();for(byte b:digest)result.append(String.format("%02x",b));return result.toString();}catch(Exception e){throw new IllegalStateException(e);}}
    private record Topic(UUID id,String name,String description){} private record State(double measured,double retention){} private record StaticCapsule(String summary,List<String> prerequisites,List<SourceStat> sources,List<QuestionPattern> assessmentPatterns){}
    public record SourceStat(String type,long documents){} public record QuestionPattern(String type,long questions){} public record Misconception(String label,String status,int occurrences,double severity){} public record Capsule(UUID topicId,String name,String summary,List<String> prerequisites,List<SourceStat> sources,List<QuestionPattern> assessmentPatterns,double measuredMastery,double retentionEstimate,double effectiveMastery,List<Misconception> misconceptions){}
}
