package com.studyos.ai;

/** Canonical operations used for provider telemetry and per-operation policies. */
public enum AiOperation {
    CHAT, QUIZ_GENERATION, CURRICULUM, LESSON_BRIEF, GRADING, TOPIC_EXTRACTION, SUMMARY, MEMORY_EXTRACTION, ASSESSMENT_EXTRACTION, EXAM_PREDICTION_VERIFICATION, RERANKING, RECONCILIATION, SYLLABUS_PARSING, RESEARCH_PLANNING, EMBEDDING
}
