package com.studyos.ai;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.*;
import java.time.Duration;
import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnProperty(name = "studyos.ai.provider", havingValue = "openai")
public class OpenAiGateway implements AiGateway {
    private final String key; private final String chatModel; private final String embeddingModel; private final ObjectMapper mapper; private final HttpClient client; private final StructuredOutputNormalizer structuredNormalizer;
    public OpenAiGateway(@Value("${OPENAI_API_KEY:}") String key, @Value("${studyos.ai.chat-model:gpt-4.1-mini}") String chatModel, @Value("${studyos.ai.embedding-model:text-embedding-3-small}") String embeddingModel, ObjectMapper mapper) { this.key = key; this.chatModel = chatModel; this.embeddingModel = embeddingModel; this.mapper = mapper; this.structuredNormalizer = new StructuredOutputNormalizer(mapper); this.client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(20)).build(); }
    @Override public AiResult<float[]> embedResult(String text,EmbeddingInputType inputType) { AiResult<List<float[]>> batch = embedBatchResult(List.of(text),inputType); return new AiResult<>(batch.value().getFirst(), batch.inputTokens(), batch.outputTokens(), batch.totalTokens(), batch.model()); }
    @Override public AiResult<List<float[]>> embedBatchResult(List<String> texts,EmbeddingInputType inputType) { try { JsonNode root = post("/embeddings", mapper.createObjectNode().put("model", embeddingModel).putPOJO("input", texts)); List<float[]> result = new ArrayList<>(); for (JsonNode item : root.path("data")) { JsonNode values=item.path("embedding"); float[] vector=new float[values.size()]; for(int i=0;i<vector.length;i++)vector[i]=(float)values.get(i).asDouble(); result.add(vector); } return result(root,result,embeddingModel); } catch(Exception e){throw new IllegalStateException("Embedding request failed",e);} }
    @Override public AiResult<String> generateResult(String systemPrompt, String userPrompt) { try { var body = mapper.createObjectNode().put("model", chatModel).put("temperature", 0.2); var messages = body.putArray("messages"); messages.addObject().put("role", "system").put("content", systemPrompt); messages.addObject().put("role", "user").put("content", userPrompt); JsonNode root=post("/chat/completions", body); return result(root, root.path("choices").get(0).path("message").path("content").asText(), chatModel); } catch (Exception e) { throw new IllegalStateException("Generation request failed", e); } }
    @Override public AiResult<String> generateResult(String systemPrompt,String userPrompt,GenerationPolicy policy){try{String selected=policy.model()==null||policy.model().isBlank()?chatModel:policy.model();var body=mapper.createObjectNode().put("model",selected).put("temperature",policy.temperature()).put("top_p",policy.topP()).put("max_tokens",policy.maxOutputTokens());if(policy.responseMode()==GenerationPolicy.ResponseMode.JSON)body.putObject("response_format").put("type","json_object");var messages=body.putArray("messages");messages.addObject().put("role","system").put("content",systemPrompt);messages.addObject().put("role","user").put("content",userPrompt);JsonNode root=post("/chat/completions",body);return result(root,root.path("choices").get(0).path("message").path("content").asText(),selected);}catch(Exception e){throw new IllegalStateException("Generation request failed",e);}}
    @Override public <T> AiResult<T> generateStructuredResult(String systemPrompt, String userPrompt, Class<T> responseType) { GenerationPolicy policy=new GenerationPolicy(AiOperation.CHAT,chatModel,2048,.1,1,false,GenerationPolicy.ResponseMode.JSON);return generateStructuredResult(systemPrompt,userPrompt,responseType,policy); }
    @Override public <T> AiResult<T> generateStructuredResult(String systemPrompt,String userPrompt,Class<T> responseType,GenerationPolicy policy){GenerationPolicy jsonPolicy=new GenerationPolicy(policy.operation(),policy.model(),policy.maxOutputTokens(),policy.temperature(),policy.topP(),policy.thinking(),GenerationPolicy.ResponseMode.JSON);AiResult<String> raw=generateResult(systemPrompt+StructuredPrompts.jsonOnly(),userPrompt,jsonPolicy);return StructuredGenerationSupport.parseStructured(mapper,this::generateResult,jsonPolicy,raw,responseType,structuredNormalizer);}
    private <T> AiResult<T> result(JsonNode root,T value,String fallbackModel) { JsonNode usage=root.path("usage"); Integer input=usage.has("prompt_tokens")?usage.get("prompt_tokens").asInt():null; Integer output=usage.has("completion_tokens")?usage.get("completion_tokens").asInt():null; Integer total=usage.has("total_tokens")?usage.get("total_tokens").asInt():null; Integer reasoning=usage.has("reasoning_tokens")?usage.get("reasoning_tokens").asInt():null; JsonNode choice=root.path("choices").isEmpty()?null:root.path("choices").get(0); String finish=choice==null?null:choice.path("finish_reason").asText(null); return new AiResult<>(value,input,output,total,root.path("model").asText(fallbackModel),finish,reasoning); }
    private JsonNode post(String path, JsonNode body) throws Exception { if (key.isBlank()) throw new IllegalStateException("OPENAI_API_KEY is not configured"); RequestDeadline.requireTimeRemaining("the OpenAI "+chatModel+" call"); var request = HttpRequest.newBuilder(URI.create("https://api.openai.com/v1" + path)).timeout(RequestDeadline.cap(Duration.ofMinutes(2))).header("Authorization", "Bearer " + key).header("Content-Type", "application/json").POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build(); var response = client.send(request, HttpResponse.BodyHandlers.ofString()); if (response.statusCode() >= 300) throw new IllegalStateException("AI provider returned HTTP " + response.statusCode() + ": " + response.body()); return mapper.readTree(response.body()); }
}
