package com.studyos.chat;

import static org.assertj.core.api.Assertions.assertThat;
import java.util.*;
import org.junit.jupiter.api.Test;

/** Regression coverage across unrelated disciplines: uploaded evidence, not Java code, defines scope. */
class GenerationScopeGroundingTest {
    @Test void rejectsABiologyTopicAbsentFromClosedEvidence(){var result=GenerationScopeRules.check(scope("cell-division.pdf","Mitosis divides one nucleus into two identical nuclei. Chromosomes align before sister chromatids separate.",List.of("Mitosis","Meiosis","Genetic Recombination")),candidate("cell-division.pdf","Meiosis","Explain how meiosis produces gametes."));assertThat(result.allowed()).isFalse();assertThat(result.unsupportedConcepts()).contains("Meiosis");}
    @Test void acceptsABiologyParaphraseSupportedByEvidence(){var result=GenerationScopeRules.check(scope("cell-division.pdf","Mitosis divides one nucleus into two identical nuclei. Chromosomes align before sister chromatids separate.",List.of("Mitosis","Meiosis")),candidate("cell-division.pdf","Alignment analysis","Analyse which chromosome arrangements can occur before chromatids separate and justify each step."));assertThat(result.allowed()).isTrue();}
    @Test void rejectsALegalTopicOutsideContractScope(){var result=GenerationScopeRules.check(contractScope(),candidate("contract.pdf","Duty of care","Analyse whether the defendant owes a duty in negligence."));assertThat(result.unsupportedConcepts()).contains("Negligence");assertThat(result.allowed()).isFalse();}
    @Test void acceptsALegalExerciseInsideScope(){var result=GenerationScopeRules.check(contractScope(),candidate("contract.pdf","Revocation conditions","Using only the cited material, derive conditions under which an offer may be revoked before acceptance and analyse counterexamples."));assertThat(result.allowed()).isTrue();}
    @Test void rejectsJavaConceptAbsentFromStreamsScope(){var result=GenerationScopeRules.check(scope("java-week6.pdf","Streams support map, filter, reduce and collectors.",List.of("Streams","Collectors","Reflection","Concurrency")),candidate("java-week6.pdf","Reflective pipeline","Use reflection to discover stream operations at runtime."));assertThat(result.unsupportedConcepts()).contains("Reflection");}
    @Test void rejectsDatabaseConceptAbsentFromNormalizationScope(){var result=GenerationScopeRules.check(scope("db-week4.pdf","Functional dependencies are used to derive 3NF and BCNF decompositions.",List.of("Functional Dependencies","Third Normal Form","Boyce Codd Normal Form","Fourth Normal Form")),candidate("db-week4.pdf","4NF design","Decompose the relation into Fourth Normal Form."));assertThat(result.unsupportedConcepts()).contains("Fourth Normal Form");}
    @Test void rejectsExplicitSourceReplacementInAnySubject(){var result=GenerationScopeRules.check(contractScope(),candidate("contract.pdf","Changed rule","Suppose that the consideration requirement is replaced with a formality requirement."));assertThat(result.unsupportedModelChanges()).contains("SOURCE_SEMANTICS_REPLACED");assertThat(result.allowed()).isFalse();}
    @Test void reportsMissingEvidenceAsClosedScopeFailure(){var empty=new GenerationScope(UUID.randomUUID(),"Week 99",List.of(99),List.of(),List.of(),List.of(),null,"",false,List.of(),"",List.of(),AcademicSemanticProfile.empty(),List.of());assertThat(GenerationScopeRules.check(empty,candidate("missing.pdf","Anything","Create a complete exercise with enough text to pass structural checks."))).matches(result->!result.allowed()&&result.scopeViolation());}
    @Test void courseWithoutExtractedTopicsStillDefersSemanticGroundingToVerifier(){var result=GenerationScopeRules.check(scope("math.pdf","A differentiable function has a derivative on the stated interval.",List.of()),candidate("math.pdf","Derivative analysis","Analyse the derivative on the stated interval and justify each conclusion from the source assumptions."));assertThat(result.allowed()).isTrue();}
    @Test void infersLectureWeeksFromDatesWithoutCourseVocabulary(){var weeks=GenerationScopeResolver.inferInstructionSequence(List.of("hash_course_2026-03-22.pdf","hash_course_2026-03-03.pdf","hash_course_2026-03-15.pdf"));assertThat(weeks).containsEntry("hash_course_2026-03-03.pdf",1).containsEntry("hash_course_2026-03-15.pdf",2).containsEntry("hash_course_2026-03-22.pdf",3);}
    @Test void explicitReferenceFreezesTheModelAndRejectsANewSetup(){var result=GenerationScopeRules.check(referencedScope(),candidate("week1.pdf","Invented instance","Consider a three-node instance with a new state table. Determine whether its target is reachable."));assertThat(result.allowed()).isFalse();assertThat(result.unsupportedModelChanges()).contains("REFERENCE_MODEL_RESTATED_OR_EXTENDED");}
    @Test void explicitReferenceAllowsNewTasksOverTheUnchangedModel(){var result=GenerationScopeRules.check(referencedScope(),candidate("week1.pdf","Exact characterization","Characterize all reachable configurations of the original model. Prove necessity and sufficiency, then critique a false converse proof."));assertThat(result.allowed()).isTrue();}
    @Test void rejectsInventedConcreteSetOrLongDataLiteral(){var setResult=GenerationScopeRules.check(referencedScope(),candidate("week1.pdf","Fixed target","Prove whether the target set {1, 2} is reachable."));assertThat(setResult.allowed()).isFalse();assertThat(setResult.unsupportedModelChanges()).contains("UNSUPPORTED_CONCRETE_DATA");var dataResult=GenerationScopeRules.check(scope("coding.pdf","The source message is 101010.",List.of()),candidate("coding.pdf","Invented frame","Validate the received frame 10101001101 using the unchanged procedure."));assertThat(dataResult.allowed()).isFalse();assertThat(dataResult.unsupportedModelChanges()).contains("UNSUPPORTED_CONCRETE_DATA");}
    @Test void allowsConcreteDataThatActuallyOccursInClosedEvidence(){var result=GenerationScopeRules.check(scope("coding.pdf","The source message is 101010 and the source set is {0}.",List.of()),candidate("coding.pdf","Source data","Analyze message 101010 and the set {0} using only the unchanged source rules."));assertThat(result.allowed()).isTrue();}

    private GenerationScope contractScope(){return scope("contract.pdf","A contract requires offer, acceptance and consideration. An offer may be revoked before acceptance unless held open by a separate promise.",List.of("Offer And Acceptance","Consideration","Negligence","Judicial Review"));}
    private GenerationScope referencedScope(){var reference=new GenerationScope.ReferenceAssessment("ref-1","The original model has state X and operation f. Construct one execution.","HOMEWORK","week1.pdf",1,1,new AcademicSemanticProfile(List.of("state"),List.of("original model has state X"),List.of(),List.of("operation f"),List.of(),List.of("construct execution"),List.of("trace operation f")));return new GenerationScope(UUID.randomUUID(),"Week 1",List.of(1),List.of(),List.of(UUID.randomUUID()),List.of("week1.pdf"),1,"homework 1",true,List.of(reference),reference.prompt(),List.of("State"),reference.semantics(),List.of());}
    private GenerationScope scope(String document,String evidence,List<String> concepts){return new GenerationScope(UUID.randomUUID(),"closed scope",List.of(1),List.of(),List.of(UUID.randomUUID()),List.of(document),null,"",false,List.of(),evidence,concepts,AcademicSemanticProfile.empty(),List.of());}
    private PredictionCandidateBatch.PredictionCandidate candidate(String document,String title,String exercise){return new PredictionCandidateBatch.PredictionCandidate(title,"Use the definitions, rules, and assumptions from the cited source unchanged. "+exercise+" ".repeat(150),List.of(new SemanticAnswerPacket.SourceRef(document,"1")),"OTHER");}
}
