package com.studyos.chat;

import static org.assertj.core.api.Assertions.assertThat;
import java.util.List;
import org.junit.jupiter.api.Test;

class PredictionVerificationRulesTest {
    @Test void detectsParameterOnlyChangesWithoutSubjectVocabulary(){assertThat(PredictionVerificationRules.localNoveltyType("filter values greater than 5 and collect them", "filter values greater than 8 and collect them")).isEqualTo("PARAMETER_ONLY_VARIANT");}
    @Test void detectsNearCopyAfterTypeAndSizeReskin(){assertThat(PredictionVerificationRules.localNoveltyType("normalize relation R with 5 attributes into BCNF", "normalize relation S with 8 attributes into BCNF")).isIn("PARAMETER_ONLY_VARIANT","NEAR_COPY");}
    @Test void detectsAnOldQuestionPaddedWithExtraSubtasks(){assertThat(PredictionVerificationRules.localNoveltyType("write pseudo code for a leader election algorithm with as few rounds as possible", "write pseudo code for a leader election algorithm with as few rounds as possible then list messages prove termination and discuss complexity")).isEqualTo("NEAR_COPY");}
    @Test void rejectsUnsupportedConcepts(){assertThat(PredictionVerificationRules.eligible(verification(false,true,"NEW_REASONING",false),false)).isFalse();}
    @Test void rejectsUnderSpecifiedExercise(){assertThat(PredictionVerificationRules.eligible(verification(true,false,"MEANINGFUL_TRANSFORMATION",false),false)).isFalse();}
    @Test void acceptsGroundedMeaningfulTransformation(){assertThat(PredictionVerificationRules.eligible(verification(true,true,"MEANINGFUL_TRANSFORMATION",false),false)).isTrue();}
    @Test void rejectsHighSolutionStrategySimilarityEvenWhenWordingDiffers(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of(),List.of(),List.of(),"MEANINGFUL_TRANSFORMATION",.7,.91,.8))).isFalse();}
    @Test void rejectsCosmeticOperatorVariant(){assertThat(PredictionVerificationRules.localNoveltyType("receive n and insert n+1 into S","receive n and insert n-1 into S")).isEqualTo("PARAMETER_ONLY_VARIANT");assertThat(PredictionVerificationRules.eligibleHardNew(verification(true,true,"PARAMETER_ONLY_VARIANT",false))).isFalse();}
    @Test void networkingRegressionIsRejectedThroughGenericSemanticComparison(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of("fairness"),List.of("natural numbers to integers"),List.of("receive increment changed to decrement"),"SHALLOW_TRANSFORMATION",.2,.95,.3))).isFalse();}
    @Test void javaTypeOnlyChangeIsRejectedThroughStrategyComparison(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of(),List.of(),List.of(),"PARAMETER_ONLY_VARIANT",.2,.96,.3))).isFalse();}
    @Test void databaseFourNfImportIsRejectedAsUnsupportedKnowledge(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of("multivalued dependencies","4NF"),List.of(),List.of(),"NEW_REASONING",.8,.3,.8))).isFalse();}
    @Test void acceptsGroundedHardNewWithDifferentReasoningStrategy(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of(),List.of(),List.of(),"NEW_REASONING",.8,.35,.8))).isTrue();}
    @Test void rejectsAValidButOnlyMediumDifficultyExerciseForHardNew(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of(),List.of(),List.of(),"NEW_REASONING",.68,.40,.65))).isFalse();}
    @Test void acceptsOnlyAtTheDocumentedHardNewThresholds(){assertThat(PredictionVerificationRules.eligibleHardNew(semanticVerification(List.of(),List.of(),List.of(),"NEW_REASONING",.60,.68,.72))).isTrue();}
    @Test void everyRequiredConceptMustBeCovered(){var value=new PredictionVerificationBatch.Verification("candidate-1",List.of("continuity","derivative"),List.of("continuity"),List.of(),List.of(),false,true,true,true,List.of(),List.of(),"NEW_REASONING",.8,false,"",.8,profile(),List.of(),List.of(),List.of(),.3,.8,"multi-step proof");assertThat(PredictionVerificationRules.eligibleHardNew(value)).isFalse();}
    @Test void detectsSameSemanticTaskDespiteMoreFormalWording(){var reference=new AcademicSemanticProfile(List.of(),List.of(),List.of(),List.of(),List.of(),List.of("define a system with specified components"),List.of("define state space and transition relations formally"));var candidate=new AcademicSemanticProfile(List.of(),List.of(),List.of(),List.of(),List.of(),List.of("formally define the system components"),List.of("define the state space and transition relation using necessary and sufficient conditions"));assertThat(PredictionVerificationRules.semanticStrategySimilarity(candidate,List.of(reference))).isGreaterThan(.55);}
    @Test void keepsDifferentReasoningStrategiesSeparate(){var reference=new AcademicSemanticProfile(List.of(),List.of(),List.of(),List.of(),List.of(),List.of("define a transition system"),List.of("state the transition relation"));var candidate=new AcademicSemanticProfile(List.of(),List.of(),List.of(),List.of(),List.of(),List.of("characterize all reachable configurations"),List.of("prove necessity then construct a computation for sufficiency"));assertThat(PredictionVerificationRules.semanticStrategySimilarity(candidate,List.of(reference))).isLessThan(.7);}

    private PredictionVerificationBatch.Verification verification(boolean grounded,boolean defined,String novelty,boolean nearCopy){return new PredictionVerificationBatch.Verification("candidate-1",List.of("source concept"),List.of("source concept"),List.of(),List.of(),false,grounded,defined,true,List.of(),List.of(),novelty,.8,nearCopy,"",.8,profile(),List.of(),List.of(),List.of(),nearCopy?1d:.4d,.8,"deeper reasoning");}
    private PredictionVerificationBatch.Verification semanticVerification(List<String> unsupportedConcepts,List<String> unsupportedDomains,List<String> unsupportedOperations,String novelty,double reasoningNovelty,double strategySimilarity,double difficulty){return new PredictionVerificationBatch.Verification("candidate-1",List.of("source concept"),List.of("source concept"),unsupportedConcepts,List.of(),false,unsupportedConcepts.isEmpty()&&unsupportedDomains.isEmpty()&&unsupportedOperations.isEmpty(),true,true,List.of(),List.of(),novelty,reasoningNovelty,false,"",.8,profile(),List.of(),unsupportedDomains,unsupportedOperations,strategySimilarity,difficulty,"deeper supported reasoning");}
    private AcademicSemanticProfile profile(){return new AcademicSemanticProfile(List.of("source concept"),List.of(),List.of(),List.of(),List.of(),List.of("analysis"),List.of("derive","justify"));}
}
